#!/usr/bin/python3
# SPDX-License-Identifier: MIT
import sys
sys.path.insert(0, "/usr/lib/python3/dist-packages")
from lintab.winmod import remount_helper_main
sys.exit(remount_helper_main(sys.argv[1:]))
