# SPDX-License-Identifier: MIT
"""A touch-friendly boot menu, using rEFInd.

GRUB's menu can only be driven with a keyboard. rEFInd shows large icons and, on firmware that exposes a touch pointer
to UEFI applications, can be tapped. LintabOS keeps GRUB for starting LintabOS itself; rEFInd is just a front door that
offers "LintabOS" and "Windows".

Safety rules, because this runs before anything else at power-on:

* **It never replaces GRUB or touches Windows' files.** rEFInd gets its own folder (``EFI/refind``) and its own firmware
  boot entry, listed first. If it can't start, the firmware falls through to the next entry (GRUB) as before.
* **It refuses to turn on when Secure Boot is enabled.** rEFInd isn't signed by a key the firmware trusts, so with Secure
  Boot on it would just fail to start. (Turn Secure Boot off in the firmware settings first, or keep using GRUB.)
* ``disable`` removes the entry and the folder and restores the previous boot order.

Touch depends on the tablet's firmware (it must offer UEFI's absolute pointer). Where it doesn't, the arrow keys and
Enter still work, and Windows and LintabOS are still one choice away.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from typing import Callable, Optional

REFIND_SOURCE = "/usr/share/refind/refind"
LINTABOS_ASSETS = "/usr/share/lintabos/refind"
STATE = "/var/lib/lintabos/boot-menu.json"
EFIVAR_SECURE_BOOT = "SecureBoot-8be4df61-93ca-11d2-aa0d-00e098032b8c"
ENTRY_LABEL = "LintabOS Boot Menu"
REFIND_LOADER = "\\EFI\\refind\\refind_x64.efi"


def secure_boot_enabled(efivars: str = "/sys/firmware/efi/efivars") -> Optional[bool]:
    """True/False for Secure Boot on/off, None when this isn't a UEFI boot (or efivars can't be read)."""
    try:
        with open(os.path.join(efivars, EFIVAR_SECURE_BOOT), "rb") as f:
            data = f.read()
    except OSError:
        return None
    return bool(data[-1]) if data else None


def render_conf(lintabos_loader: Optional[str], windows: bool) -> str:
    """The refind.conf: big icons, touch on, only two choices (LintabOS and Windows)."""
    lines = [
        "# LintabOS boot menu (rEFInd). Generated by lintab-boot-menu; `lintab-boot-menu disable` removes it.",
        "timeout 10",
        "enable_touch",                      # enable_touch and enable_mouse are mutually exclusive in rEFInd
        "big_icon_size 256",
        "small_icon_size 96",
        "hideui singleuser,hints,editor",
        "showtools shutdown,reboot,firmware",
        "scanfor manual",                    # list only what is spelled out below
        "banner background.png",
        "banner_scale fillscreen",
        "resolution max",
        "default_selection 1",
        "",
    ]
    if lintabos_loader:
        lines += ['menuentry "LintabOS" {', "    icon /EFI/refind/icons/lintabos.png", f"    loader {lintabos_loader}", "}", ""]
    if windows:
        lines += ['menuentry "Windows" {', "    icon /EFI/refind/icons/os_win.png",
                  "    loader /EFI/Microsoft/Boot/bootmgfw.efi", "}", ""]
    return "\n".join(lines)


def new_boot_order(old: list[str], new_id: str) -> list[str]:
    """New entry first, the rest unchanged (and without a duplicate of the new one)."""
    return [new_id] + [b for b in old if b != new_id]


def parse_efibootmgr(text: str) -> tuple[list[str], dict[str, str]]:
    """Return (BootOrder, {id: label}) from `efibootmgr` output."""
    order = []
    entries = {}
    for line in text.splitlines():
        m = re.match(r"BootOrder:\s*(\S+)", line)
        if m:
            order = m.group(1).split(",")
        m = re.match(r"Boot([0-9A-Fa-f]{4})\*?\s+(.*)", line)
        if m:
            entries[m.group(1).upper()] = m.group(2).split("\t")[0].strip()
    return order, entries


def _run(argv: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run(argv, capture_output=True, text=True)


def _disk_and_partition(esp: str, run: Callable) -> tuple[str, str]:
    source = run(["findmnt", "-no", "SOURCE", esp]).stdout.strip()
    parent = run(["lsblk", "-no", "PKNAME", source]).stdout.strip().splitlines()[0]
    partn = run(["lsblk", "-no", "PARTN", source]).stdout.strip().splitlines()[0]
    return f"/dev/{parent}", partn


class BootMenuError(RuntimeError):
    pass


def ensure_refind(run: Callable = _run, refind_source: str = REFIND_SOURCE) -> bool:
    """Install Debian's ``refind`` package if it is missing. Returns True when it had to be installed.

    The package's own default is to install itself onto the EFI partition and take over booting, which we do not want
    (this module does that itself, next to GRUB, with an undo). So that debconf answer is set to "false" BEFORE the
    package is installed; if the answer can't be stored, nothing is installed.
    """
    if os.path.exists(os.path.join(refind_source, "refind_x64.efi")):
        return False
    seed = run(["sh", "-c", "echo 'refind refind/install_to_esp boolean false' | debconf-set-selections"])
    if getattr(seed, "returncode", 0) != 0:
        raise BootMenuError("Could not tell the refind package not to touch the boot partition; not installing it.")
    got = run(["env", "DEBIAN_FRONTEND=noninteractive", "apt-get", "install", "-y", "--no-install-recommends", "refind"])
    if getattr(got, "returncode", 0) != 0:
        raise BootMenuError("Installing the refind package failed (is this computer online?):\n"
                            + (getattr(got, "stderr", "") or "").strip())
    return True


def enable(esp: str = "/boot/efi", efivars: str = "/sys/firmware/efi/efivars", run: Callable = _run,
           refind_source: str = REFIND_SOURCE, assets: str = LINTABOS_ASSETS, state_path: str = STATE) -> list[str]:
    """Install rEFInd next to GRUB and make it the first boot choice. Returns what it did (for display and tests)."""
    log: list[str] = []
    sb = secure_boot_enabled(efivars)
    if sb is None:
        raise BootMenuError("This computer isn't booted in UEFI mode (or the firmware variables can't be read).")
    if sb:
        raise BootMenuError(
            "Secure Boot is turned on, and rEFInd isn't signed by a key the firmware trusts, so it would not start.\n"
            "Either turn Secure Boot off in the firmware settings and run this again, or keep using the GRUB menu.")
    if ensure_refind(run, refind_source):
        log.append("installed the refind package (its own boot-partition install is switched off)")
    binary = os.path.join(refind_source, "refind_x64.efi")
    if not os.path.exists(binary):
        raise BootMenuError("rEFInd is not installed (package `refind`).")
    if not os.path.isdir(esp):
        raise BootMenuError(f"The EFI partition isn't mounted at {esp}.")

    target = os.path.join(esp, "EFI", "refind")
    os.makedirs(os.path.join(target, "icons"), exist_ok=True)
    shutil.copy(binary, os.path.join(target, "refind_x64.efi"))
    shutil.copy(os.path.join(refind_source, "icons", "os_win.png"), os.path.join(target, "icons", "os_win.png"))
    for name, dest in (("lintabos.png", "icons/lintabos.png"), ("background.png", "background.png")):
        src = os.path.join(assets, name)
        if os.path.exists(src):
            shutil.copy(src, os.path.join(target, dest))
    log.append(f"copied rEFInd to {target}")

    lintabos_loader = next((p for p in ("/EFI/LintabOS/shimx64.efi", "/EFI/LintabOS/grubx64.efi")
                            if os.path.exists(os.path.join(esp, p.lstrip("/")))), None)
    windows = os.path.exists(os.path.join(esp, "EFI/Microsoft/Boot/bootmgfw.efi"))
    with open(os.path.join(target, "refind.conf"), "w") as f:
        f.write(render_conf(lintabos_loader, windows))
    log.append(f"menu entries: {'LintabOS ' if lintabos_loader else ''}{'Windows' if windows else ''}".strip())

    before = run(["efibootmgr"])
    old_order, entries = parse_efibootmgr(before.stdout)
    for boot_id, label in entries.items():          # replace an earlier copy instead of piling up entries
        if label == ENTRY_LABEL:
            run(["efibootmgr", "-B", "-b", boot_id])
            old_order = [b for b in old_order if b != boot_id]
    disk, part = _disk_and_partition(esp, run)
    created = run(["efibootmgr", "-c", "-d", disk, "-p", part, "-l", REFIND_LOADER, "-L", ENTRY_LABEL])
    order_now, entries_now = parse_efibootmgr(created.stdout)
    new_id = next((i for i, label in entries_now.items() if label == ENTRY_LABEL), None)
    if not new_id:
        raise BootMenuError("The firmware boot entry could not be created: " + (created.stderr or created.stdout).strip())
    run(["efibootmgr", "-o", ",".join(new_boot_order(old_order, new_id))])
    os.makedirs(os.path.dirname(state_path), exist_ok=True)
    with open(state_path, "w") as f:
        json.dump({"entry": new_id, "previous_order": old_order, "esp": esp}, f)
    log.append(f"boot entry Boot{new_id} created and placed first (previous order saved)")
    return log


def disable(run: Callable = _run, state_path: str = STATE) -> list[str]:
    log: list[str] = []
    try:
        with open(state_path) as f:
            state = json.load(f)
    except (OSError, ValueError):
        raise BootMenuError("The touch boot menu isn't enabled (no saved state found).")
    run(["efibootmgr", "-B", "-b", state["entry"]])
    if state.get("previous_order"):
        run(["efibootmgr", "-o", ",".join(state["previous_order"])])
    shutil.rmtree(os.path.join(state["esp"], "EFI", "refind"), ignore_errors=True)
    os.remove(state_path)
    log.append("removed the boot entry and EFI/refind; previous boot order restored")
    return log


def main(argv: Optional[list[str]] = None) -> int:
    ap = argparse.ArgumentParser(prog="lintab-boot-menu", description=__doc__.split("\n\n")[0])
    ap.add_argument("action", choices=["status", "enable", "disable"], nargs="?", default="status")
    ap.add_argument("--esp", default="/boot/efi")
    args = ap.parse_args(argv)
    if args.action == "status":
        sb = secure_boot_enabled()
        print("Secure Boot:", {None: "unknown (not UEFI?)", True: "on (the touch menu can't be used)", False: "off"}[sb])
        print("touch boot menu:", "enabled" if os.path.exists(STATE) else "not enabled")
        return 0
    if os.geteuid() != 0:
        print("run this as root (sudo)", file=sys.stderr)
        return 1
    try:
        for line in (enable(args.esp) if args.action == "enable" else disable()):
            print(line)
    except BootMenuError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
