# Intel Integrated Sensor Hub -> HID sensors -> IIO (accelerometer, gyro, ALS)
intel_ish_ipc
intel_ishtp_hid
hid_sensor_hub
hid_sensor_accel_3d
hid_sensor_gyro_3d
hid_sensor_als
hid_sensor_rotation
hid_sensor_trigger
fuse
